# -*- coding: utf-8 -*-
"""reconcile

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C278KK54DC1dAHBbgvP3GsPp9Q7QQ5IT

**1. Loading both files**
"""

import pandas as pd

df_gateway = pd.read_csv('gateway_export.csv')
df_ledger = pd.read_csv('ledger.csv')
display(df_gateway)
display(df_ledger)

"""**Creating a Reconciliation Function**




"""

import pandas as pd

def reconcile_payments(ledger_df, gateway_df, id_column='transaction_id', amount_column='amount_inr', status_column='status'):
    """
    Reconciles ledger and gateway dataframes and returns four discrepancy DataFrames.
    """
    # Unique ID sets
    ledger_ids = set(ledger_df[id_column])
    gateway_ids = set(gateway_df[id_column])

    # 1. Missing in Gateway (~5%)
    missing_in_gateway_ids = ledger_ids - gateway_ids
    missing_in_gateway = ledger_df[ledger_df[id_column].isin(missing_in_gateway_ids)].copy()

    # 2. Missing in Ledger / Extra in Gateway (~2%)
    missing_in_ledger_ids = gateway_ids - ledger_ids
    missing_in_ledger = gateway_df[gateway_df[id_column].isin(missing_in_ledger_ids)].copy()

    # Pairwise comparison on common transactions
    common_ids = ledger_ids & gateway_ids
    ledger_common = ledger_df[ledger_df[id_column].isin(common_ids)]
    gateway_common = gateway_df[gateway_df[id_column].isin(common_ids)]

    merged = ledger_common.merge(
        gateway_common[[id_column, amount_column, status_column]],
        on=id_column,
        suffixes=('_ledger', '_gateway')
    )

    # 3. Amount Mismatches (~3%)
    merged['difference'] = merged[f'{amount_column}_ledger'] - merged[f'{amount_column}_gateway']
    amount_mismatches = merged[merged['difference'] != 0].copy()

    # 4. Status Mismatches (~2%)
    status_mismatches = merged[merged[f'{status_column}_ledger'] != merged[f'{status_column}_gateway']].copy()

    return missing_in_gateway, missing_in_ledger, amount_mismatches, status_mismatches

"""Using Reconcilation Function"""

# Run reconciliation
missing_gw, missing_lg, amount_diffs, status_diffs = reconcile_payments(df_ledger, df_gateway)

# Print Discrepancy Counts & Check against expectations
total_ledger = len(df_ledger)
total_issues = len(missing_gw) + len(missing_lg) + len(amount_diffs) + len(status_diffs)

print("=== RECONCILIATION DISCREPANCY REPORT ===")
print(f"Total Ledger Records: {total_ledger}")
print(f"Total Discrepancies Found: {total_issues} ({total_issues/total_ledger:.1%})")
print("----------------------------------------")
print(f"1. Missing in Gateway: {len(missing_gw)} ({len(missing_gw)/total_ledger:.1%})  [Expected ~5%]")
print(f"2. Missing in Ledger:  {len(missing_lg)} ({len(missing_lg)/total_ledger:.1%})  [Expected ~2%]")
print(f"3. Amount Mismatches:  {len(amount_diffs)} ({len(amount_diffs)/total_ledger:.1%})  [Expected ~3%]")
print(f"4. Status Mismatches:  {len(status_diffs)} ({len(status_diffs)/total_ledger:.1%})  [Expected ~2%]")

"""Missing in Gateway"""

# Access specific issues
print("=== Missing in Gateway ===")

# Calculate totals directly from missing_gw
total_count = len(missing_gw)
total_amount = missing_gw['amount_inr'].sum()

print(f"Total Transactions Missing in Gateway: {total_count}")
print(f"Total Amount Missing in Gateway: ₹{total_amount:,.2f}\n")

# Display the transaction list
print(missing_gw[['transaction_id', 'amount_inr']])

"""Missing in Ledger"""

print("=== Missing in Ledger ===")

# Calculate totals directly from missing_lg
total_count = len(missing_lg)
total_amount = missing_lg['amount_inr'].sum()

print(f"Total Transactions Missing in Ledger: {total_count}")
print(f"Total Amount Missing in Ledger: ₹{total_amount:,.2f}\n")

# Display the transaction list
print(missing_lg[['transaction_id', 'amount_inr']])

"""Amount Mismatches"""

print("=== Amount Mismatches ===")

# Calculate total count and total net/absolute discrepancy
total_count = len(amount_diffs)
total_discrepancy = amount_diffs['difference'].abs().sum()

print(f"Total Amount Mismatched Transactions: {total_count}")
print(f"Total Discrepancy Amount: ₹{total_discrepancy:,.2f}\n")

# Display the transaction list
print(amount_diffs[['transaction_id', 'amount_inr_ledger', 'amount_inr_gateway', 'difference']])

"""Status Mismatch"""

print("=== Status Mismatches ===")

# Calculate total count of status mismatches
total_count = len(status_diffs)

print(f"Total Transactions with Status Mismatch: {total_count}\n")

if total_count > 0:
    print("⚠️  CRITICAL — Status Discrepancies Found:")
    print(status_diffs[['transaction_id', 'amount_inr_ledger', 'status_ledger', 'status_gateway']])